### ISSUE TITLE
Image header is not copied back fully

### ISSUE THREAD

**Issue by SlicerMorph** [SlicerMorph/MEMOS#12]
For images that have different spacing/orientation/origin than trained network, we reset them to default and copy back them to the resultant segmentation. it appears origin is not carried over. 

To replicate, load a sample data, clone it, change the origin of the clone image and run them back to back to see that segmentation belonging to clone is not overlaid correctly.

**Comment by muratmaga** [comment]
@smrolfe this is still not fixed. Also fix the segmentaiton labelmap dimension size. 

Recall that segmentations generated by MEMOs do not have the same dimensions as the original volume. When you are doing the conversion from labelmap to segmentation, are you restricting to the minimum extend for some reason

**Comment by smrolfe** [comment]
This issue with the origin should have been solved in: https://github.com/SlicerMorph/SlicerMEMOS/commit/803731dfe6f44d31cc1c93094386b71c324a6319

I cannot replicate the error, could you let me know what image/steps you are using?

The segmentation/labelmap dimension was a separate issue. The default image geometry was being used on saving or conversion. I have now added a reference volume to the segmentation that solves this issue in: https://github.com/SlicerMorph/SlicerMEMOS/commit/23e88d0610c2474559ca90477b1ab3ddb7b26378

**Comment by muratmaga** [comment]
it still reproduces for me. Download the sample data. Clone it. Edit the origin of the cloned image. Run the MEMOs on the cloned image, see that the segmentaiton does not have the correct image origin.

**Comment by smrolfe** [comment]
The segmentation dimension/origin is corrected in the changes I pushed today.
