### ISSUE TITLE
Issues identified during trying out this extension

### ISSUE THREAD

**Issue by fedorov** [SlicerMorph/MEMOS#13]
I wanted to try it out on MR images of the mouse. I followed the installation instructions accompanying the paper, using stable release of Slicer (5.2.1) and ran into the following issues.

1. I installed PyTorch Utils extension, but it reported that NVIDIA driver was not found, even though running `nvidia-smi` from the terminal or from the python console recognized the GPU. I installed pytorch from the command line, and after this I could see pytorch libraries in the PyTorch Utils interface, but still no NVIDIA drivers.
2. When I tried to run segmentation, Slicer crashed.

I tried this on one of the images available from a PDMR collection in IDC (here's one example: https://viewer.imaging.datacommons.cancer.gov/viewer/2.25.279830772673637264923333307592482705135?SeriesInstanceUID=2.25.94829331130993737408035901430728862042).

I understand this model was not developed/tested for MR or for "adult mouse", but I thought I report those issues in case this can help making the extension more robust.

**Comment by muratmaga** [comment]
Thanks @fedorov 

Now torch installation is handled by the PyTorch extension, which is a dependency. You no longer need to do this manually, but you should try with the latest stable (I think the extensions for older stable goes stale).

**Comment by fedorov** [comment]
@muratmaga I mis-spoke. I am using Slicer 5.2.2, the latest stable. This is on a JetStream VM instance, so I could maybe even add you to that VM, if you would like to debug. But it is not in the critical path for me, I am just letting you know if you want to investigate.

On a related topic, can you recommend any open source tools - in Slicer or outside - that are available for segmentation of mouse CT or MR?

**Comment by muratmaga** [comment]
Interesting, I have been running MEMOS on JS2 for couple months no issues (since we switch to PyUtils extension as opposed to manual install of Torch). See the screenshot.  I literally didn't need to do anything beyond, install PyUtils, run auto detection, and let it do it job. Then install MEMOS. 

<img width="860" alt="image" src="https://github.com/SlicerMorph/SlicerMEMOS/assets/21285140/6926a7f8-81f6-47f3-8c99-dcbd20cea523">

**Comment by muratmaga** [comment]
> On a related topic, can you recommend any open source tools - in Slicer or outside - that are available for segmentation of mouse CT or MR?

We don't use MR, so my knowledge is prettty limited. 
I think there are a few mouse atlases that were published before. You might want to checkout http://www.mouseimaging.ca/technologies/mouse_atlas/C57Bl6j_mouse_atlas.html

perhaps then you can proceed with the Atlas-based segmentation using something like ANTsR or ANTsPy.
