### ISSUE TITLE
Change the default segmentation data type to unsigned 8 bit

### ISSUE THREAD

**Issue by muratmaga** [SlicerMorph/MEMOS#17]
Right now memos output the segmentation in the data type of original volume. This causes problems if the original volume is float (resultant labelmap cannot be edited by Slicer), and it also makes the outputs unnecessarily large. Since there are only 51 classes, let make sure the output segmentation is of datatype unsigned 8bit.

**Comment by smrolfe** [comment]
Resolved here: [5f411e1](https://github.com/SlicerMorph/SlicerMEMOS/commit/5f411e1ff895313cde38db21587169e12c1d7fa8)
