### ISSUE TITLE
Module fails with: "ModuleNotFoundError: No module named 'einops'"

### ISSUE THREAD

**Issue by lassoan** [SlicerMorph/MEMOS#8]
Installed on Slicer-5.2.1, downloaded sample data set, downloaded model, clicked Apply - then disappointment :(

```
Traceback (most recent call last):
  File "C:/Users/andra/AppData/Local/NA-MIC/Slicer 5.2.1-monaitest/NA-MIC/Extensions-31317/MEMOS/lib/Slicer-5.2/qt-scripted-modules/MEMOS.py", line 290, in onApplySingleButton
    logic.runSingle(tempVolumeFile, self.modelPathSingle.currentPath, tempOutputPath)
  File "C:/Users/andra/AppData/Local/NA-MIC/Slicer 5.2.1-monaitest/NA-MIC/Extensions-31317/MEMOS/lib/Slicer-5.2/qt-scripted-modules/MEMOS.py", line 381, in runSingle
    import einops
ModuleNotFoundError: No module named 'einops'
```

**Comment by SlicerMorph** [comment]
I am not replicating this on my end with fresh installations. This is windows right?

**Comment by smrolfe** [comment]
Hi @lassoan can you let me know what happens when you manually install with `slicer.util.pip_install('einops')`

**Comment by lassoan** [comment]
I've found a serious issue with how the module starts. The module calls [installLibs](https://github.com/SlicerMorph/SlicerMEMOS/blob/1c2495b210e5316bcc87bd6ea42c7930cb22619f/MEMOS/MEMOS.py#L67) in the module object constructor! This is a significant problem even when only minor packages are installed, but for extremely large packages like pytorch then it is essentially it prevents Slicer to start up for potentially tens of minutes (if the required pytorch version was not already installed and available in the pip download cache on the computer). The user of course does not know that Slicer is actually still starting up, he restarts Slicer, so now we have a Slicer running in the background trying to install a number of packages, while another Slicer instance is still running. The result is quite likely partially installated Python packages (which can cause the "no module named einops" error reported above).

To fix this:
- only do trivial operations in the module class constructor (what is shown in the module template), absolutely no pip install (it would block Slicer application startup if there is no or slow network or installing large packages)
- do not rely on the user reading documentation in advance and installing pytorch using PyTorch extension, but make PyTorch extension a dependency of MEMOS and use it to install pytorch
- move installation of required library at the point of first use (e.g., when the user clicks Apply) - luckily in TotalSegmentator we have a robust example of how to install pytorch and other libraries (tested by almost 2000 people on Windows, 200 linux, 300 macos; we got only a handful of error reports, and we could resolve most of them). I would recommend to copy the implementation from here: https://github.com/lassoan/SlicerTotalSegmentator/blob/d9b4f6e7a2eae05d099836aa8d314a59df066262/TotalSegmentator/TotalSegmentator.py#L571-L626

**Comment by smrolfe** [comment]
Thanks @lassoan we were hesitant to add an unnecessary dependency, but I think this makes a lot of sense.

**Comment by lassoan** [comment]
PyTorch extension is a very lightweight dependency, it just installs light-the-torch, a tiny Python package that can determine what pytorch version is compatible with the system and can install it.

**Comment by SlicerMorph** [comment]
Fixed with adding pytorach dependency
