### ISSUE TITLE
Link to sample data set is incorrect

### ISSUE THREAD

**Issue by lassoan** [SlicerMorph/MEMOS#9]
None of the sample data downloads seem to work. They all return a nrrd file in a zip file containing HTML document with a link to the actual download URL.

Please also add at least one sample data set to the SampleData module that is known to work with the model. This was in the [module template](https://github.com/Slicer/Slicer/blob/4f3d97c612b417cb8fe1c5688910f71d23a35852/Utilities/Templates/Modules/Scripted/TemplateKey.py#L37-L74).

You may consider uploading the chosen single sample data set as release asset in this repository to avoid depending on external hosting (you'll not know when the external download link breaks).

**Comment by SlicerMorph** [comment]
It is not our data to republish (I am not sure about their policies), but I will add one dataset to the repo and then ask for permission from IMPC.

**Comment by lassoan** [comment]
If you don't want to republish then you can download from their link. You can add acknowledgment to MEOS module help and in tooltip in the sample data.

**Comment by SlicerMorph** [comment]
They don't provide a directly downloadable link. I did include this one until we have a proper solution. 
https://raw.githubusercontent.com/SlicerMorph/SampleData/master/IMPC_sample_data.nrrd

**Comment by lassoan** [comment]
They do provide a direct download link now. Open html content in the nrrd file in the zip file that you download from the link that is in the module documentation. It is now a direct download link. For example, https://api.mousephenotype.org/tracker/media/emb2/8/9/0/19/843/40869/603915_56.nrrd

**Comment by SlicerMorph** [comment]
The inconsistency of the data provided was one of the challenges we faced. Let's see how long they will maintain this.
